version: '3'

volumes:
  media: {}
  static: {}

services:
  redis:
    restart: always
    image: redis:latest

  app:
    restart: always
    build: .
    command: bash -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate && daphne -b 0.0.0.0 -p 8001 todo.asgi:application"
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - media/:/media/
      - static/:/static/
    env_file:
      - .env

  celery:
    image: celery:latest
    restart: always
    build: .
    command: celery -A todo worker -l info
    depends_on:
      - redis
      - app
    env_file:
      - .env

  nginx:
    restart: always
    image: nginx:latest
    build: ./nginx
    volumes:
      - media/:/media/
      - static/:/static/
    ports:
      - "80:80"
    environment:
      - HOST_NAME
    env_file:
      - ./.env
    depends_on:
      - app
