# Generated by Django 3.1.7 on 2021-10-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='core.TodoItem', verbose_name='Задачи'),
        ),
    ]
